route:
  group_by: ['alertname']
  #group_wait: 10s
  #group_interval: 10s
  #repeat_interval: 1h
  receiver: 'webalert'

receivers:
- name: 'webalert'
  - 'localhost:9093'

inhibit_rules:
- source_match:
severity: 'critical'
target_match:
severity: 'warning'
equal: ['alertname', 'dev', 'instance']
