global:
  scrape_interval: 10s
  scrape_timeout: 5s
  evaluation_interval: 1m

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus' # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
    scrape_interval: 10s # Override the global default and scrape targets from this job every 5 seconds.
    scrape_timeout: 3s
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'wmi exporter'
    static_configs:
      - targets: ['host.docker.internal:9182']

  - job_name: node
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9100']

  - job_name: pushgateway
    honor_labels: true
    static_configs:
      - targets:
          - 'pushgateway:9091'
        labels:
          instance: 'pushgateway'

  - job_name: cadvisor
    scrape_interval: 5s
    scrape_timeout: 2s
    honor_labels: true

    static_configs:
      - targets: ['cadvisor:8080']


alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'localhost:9093'

rule_files:
  - "prometheus.rules.yml" #ссылка на файл в контейнере prometheus